### ISSUE TITLE
Docker compose boilerplate

### ISSUE THREAD

**Issue by INF800** [tiangolo/fastapi#1890]
Hi,

Can anyone share working `docker-compose.yml` file for basic FastAPI code.
Preferred if connected to PostgreSQL

Thanks,
Rakesh

**Comment by IanSaucy** [comment]
You might find the `docker-compose.yml` file provided in [this project useful](https://github.com/Buuntu/fastapi-react). It's much simpler than the [full-stack setup ](https://github.com/tiangolo/full-stack-fastapi-postgresql)provided and a bit easier to understand(although it lacks much of the fancier items). 

Using that repo, if you wanted the most basic setup, I'd just use the `backend` and `postgres` services and you should be good to go!

**Comment by rakesh4real** [comment]
Hi @IanSaucy 
Thanks for your reply. I am quite new to docker if you don't mind can you please paste minimal `Dockerfile` and `docker-compose.yml` file. Hope I am not asking much

**Comment by IanSaucy** [comment]
It's hard to post docker files without knowing the structure of your entire project. Docker files do not include your source code(ie all the routes for fastAPI etc), instead they say where and how it should run the code you already have -- thus it needs to factor in your file structure. If you have a repo with your project or something I might be able to help. 

I would look up some basic docker and docker-compose info/tutorials. Personally, I found it useful to understand the technology a little before implementing it into a project otherwise you end up copy-pasting without an idea of what is happening. 

Maybe one of these tutorial would be helpful? Also, I really think the react or full stack example linked in the previous example would be a good starting point. 

https://medium.com/@mike.p.moritz/using-docker-compose-to-deploy-a-lightweight-python-rest-api-with-a-job-queue-37e6072a209b
https://testdriven.io/blog/fastapi-crud/

Good luck!

**Comment by rakesh4real** [comment]
Thank you @IanSaucy Links look amazing I will definitely check them out. I was trying docker for [this minimal fast-api temlpate](https://github.com/rakesh4real/fastapi-template).
The docker files that I have already tried are in readme file. But couln't get them working

**Comment by mickeypash** [comment]
Hey @rakesh4real,
Here is a version of these files

Dockerfile
- uses Python 3.8
- exposes the app on host port 8000
- starts the app

```Dockerfile
FROM python:3.8.1

ENV PYTHONUNBUFFERED 1

EXPOSE 8000
WORKDIR /app

COPY requirements ./
RUN pip install -r requirements.txt

COPY . ./

CMD uvicorn --host=0.0.0.0 app.main:app
```

docker-compose.yml
- Runs the app service
- Runs a Postgres database (but feel free to change that to something else or remove it)

```yaml
version: '3.7'

services:

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URL: "postgres://postgres:test@db/postgres"
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test
```

Hope this helps
