### ISSUE TITLE
[BUG] exclusiveMinimum and exclusiveMaximum should be boolean

### ISSUE THREAD

**Issue by eu42** [tiangolo/fastapi#240]
**Describe the bug**
exclusiveMinimum and exclusiveMaximum should be of type boolean

**To Reproduce**
A field with greater than property is generated as:
```
end:
    exclusiveMinimum: 0.0
    type: number
```

**Expected behavior**

It should be:
```
end:
    exclusiveMinimum: true
    minimum: 0.0
    type: number
```

**Environment:**
- OS: Linux and macOS
- FastAPI version 0.22.0
- Python version 3.7

**Additional context**
According to OpenAPI, these fields should be boolean as listed [here](https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.yaml).
