### ISSUE TITLE
Root path is applied 2 times when using root_path

### ISSUE THREAD

**Issue by mindej** [tiangolo/fastapi#2872]
Here is error: 
![image](https://user-images.githubusercontent.com/1636250/109177801-e079b280-7790-11eb-8fce-50257e88090a.png)

Python 3.7.8
fastapi 0.63.0

Run configuration:
`uvicorn.run("app:app", host="0.0.0.0", port=port, reload=True)`

I think the error is in the path here is console log:
`127.0.0.1:54913 - "GET /api/v1/api/v1/openapi.json HTTP/1.1" 404 Not Found`
Here is double path: /api/v1/**api/v1/**

Doc path is wrong http://localhost:8080/docs I expect it to be: http://localhost:8080/api/v1/docs

Here is the test code to reproduce 'test_app.py' file: 
```
import uvicorn
import json
from fastapi import FastAPI, APIRouter, Response
from fastapi.responses import RedirectResponse

app = FastAPI(title="Root path test", root_path="/api/v1")

@app.post("/test-call ", tags=["test"])
def ping():
    return Response(
        json.dumps(dict(ping='pong')), 
        headers={'Content-Type':'application/json'})

@app.get("/")
def read_typer():
    return RedirectResponse('/docs')


if __name__ == "__main__":
    uvicorn.run("test_app:app", host="0.0.0.0", port=8080, reload=True)
```

**Comment by ycd** [comment]
Can you share your proxy settings?

**Comment by mindej** [comment]
I do not have a proxy. It is a local server. You can run it and test it locally. 

Please run a file to reproduce: `python3.7 test_app.py`

**Comment by insomnes** [comment]
@mindej `root_path` is designated for behind the proxy cases, where you have something like NGINX, which publishes your web server with some prefix, like "/api/v1"

**Comment by krishnardt** [comment]
```
temp = APIRouter()
app = FastAPI()
app.include_router(temp, prefix='/api/v1')
```

this might help you.

if you require the path should be **api/v1/docs**, then you can update in the docs_url parameter of fastapi.

```
docs_url='/api/v1/docs',
redoc_url='/api/v1/redoc',
```

**Comment by NicolasRondon** [comment]
Like krishnardt  says You can change the docs ulr. [Documentation](https://fastapi.tiangolo.com/tutorial/metadata/#docs-urls)

**Comment by zxl777** [comment]
I also found this double bug. I followed the https://fastapi.tiangolo.com/advanced/behind-a-proxy operation, but did not succeed.

I think there should be a bug, please test it.

**Comment by ycd** [comment]
This is the expected behaviour, not a bug.

**Comment by intangir** [comment]
im seeing similar irritating issues with both lambdas served over an api gatewith with a prefix path

and locally, using both root_path and a router with a prefix

reading the EXACT DOCS from here https://fastapi.tiangolo.com/advanced/behind-a-proxy/ and setting up the root_path..

also using router it isn't working..

it always just serves things up as if the entire path is always the entire path regardless..

its incredibly infuriating reading doc after doc after doc and following all the the instructures verbatim and not a damn new thing making a damn bit of difference in how its served..

then finding people with the exact same issue being told 'expected behavior not a bug'

then what are these worthless features for? how should they work?

**Comment by insomnes** [comment]
Maybe i totally miss your point, but here are details about my suggestiions.
### Router
If you need to place some family of handler with same prefix with direct publishing with your web server, you will need `APIRouter`:

```python3
from fastapi import FastAPI
from fastapi.routing import APIRouter


prefix_router = APIRouter()


@prefix_router.get("/path")
def handler():
    return "Hello world!"


app = FastAPI()
app.include_router(
    prefix_router,
    prefix="/prefix"
)
```
===>
```
http http://127.0.0.1:8000/prefix/path
HTTP/1.1 200 OK
content-length: 14
content-type: application/json
date: Mon, 10 May 2021 10:46:09 GMT
server: uvicorn

"Hello world!"
```

Docs at http://127.0.0.1:8000/docs 
![image](https://user-images.githubusercontent.com/16958893/117648654-27bfee80-b197-11eb-908d-ba0fff84beab.png)


### Root path
If you need to **_PUBLISH_** your app via some proxy with some **_ADDED_** prefix, you should use `root_path`:
```python3
from fastapi import FastAPI

app = FastAPI(root_path="/prefix")


@app.get("/path")
def handler():
    return "Hello world!"
```
Going directly to app docs at http://127.0.0.1:8000/docs will show error:

![image](https://user-images.githubusercontent.com/16958893/117649076-c0566e80-b197-11eb-9a1a-cc3d380545e1.png)


Going through proxy like traefik in docs in which you PUBLISHED your server with some prefix will help.
Publishing config for traefik (kinda same as FastAPI mentioned docs shows):
`traefik.toml`
```toml
[entryPoints]
  [entryPoints.http]
    address = ":9999"

[providers]
  [providers.file]
    filename = "routes.toml"
```

`routes.toml`
```toml
[http]
  [http.middlewares]

    [http.middlewares.api-stripprefix.stripPrefix]
      prefixes = ["/prefix"]

  [http.routers]

    [http.routers.app-http]
      entryPoints = ["http"]
      service = "app"
      rule = "PathPrefix(`/prefix`)"
      middlewares = ["api-stripprefix"]

  [http.services]

    [http.services.app]
      [http.services.app.loadBalancer]
        [[http.services.app.loadBalancer.servers]]
          url = "http://127.0.0.1:8000"
```

Request through traefik:
```
http http://127.0.0.1:9999/prefix/path 
HTTP/1.1 200 OK
Content-Length: 14
Content-Type: application/json
Date: Mon, 10 May 2021 10:59:41 GMT
Server: uvicorn

"Hello world!"
```

Docs through traefik at http://127.0.0.1:9999/prefix/docs 
![image](https://user-images.githubusercontent.com/16958893/117649756-9487b880-b198-11eb-8f7a-751ccbff4eef.png)
