### ISSUE TITLE
Failed to open the swagger documentation after hosting it on AWS

### ISSUE THREAD

**Issue by kashyapm94** [tiangolo/fastapi#3110]
This question is more of a follow-up from issue #2787 

I am hosting the app on API Gateway using Gitlab CI/CD and serverless. I have a couple of routes:

- prices
- prices/update

I have generated an API key to protect these routes. The key is generated directly via serverless. Naturally, I don't want the swagger documentation route to be protected. But when I host the app, the swagger documentation shows the following error:

![error](https://user-images.githubusercontent.com/35066641/115529366-246dcd00-a293-11eb-89b2-eda725af28a5.png)

The `main.py` file:

```
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from mangum import Mangum

from app.api.v1 import prices
from app.core.config import settings
from app.database.session import Base, engine

Base.metadata.create_all(bind=engine)

app = FastAPI(
    title=settings.PROJECT_NAME,
    version=0.1,
    root_path="/dev/"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.BACKEND_CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
app.include_router(prices.router)

handler = Mangum(app)

```

My `serverless.yml` file

```
service: myapp

plugins:
  - serverless-python-requirements
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_DEFAULT_REGION}
  endpointType: REGIONAL
  lambdaHashingVersion: 20201221
  apiGateway:
    apiKeys:
        - myapikey
    shouldStartNameWithService: true

package:
  patterns:
    - '!app/tests/**'
    - '!.coveragerc'
    - '!.gitlab-ci.yml'
    - '!package.json'
    - '!package-lock.json'
    - '!Pipfile'
    - '!Pipfile.lock'
    - '!README.md'

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  my-app:
    handler: app.main.handler
    timeout: 30
    memorySize: 150
    events:
      - http:
          path: docs # <-- This is the page for swagger documentation
          method: get
      - http:
          path: prices
          method: get
          private: true # <-- protects the route with the apikey
      - http:
          path: prices/update
          method: post
          private: true # <-- protects the route with the apikey
```

**Comment by frankie567** [comment]
When loading the interactive docs, Swagger will try to load the OpenAPI specification which live in your case at `/dev/openapi.json`. So I guess, you should also configure this route in your `serverless.yml` file.

**Comment by kashyapm94** [comment]
As suggested by @frankie567, doing the following solved the problem:

```
      - http:
          path: /docs
          method: ANY
          private: false
      - http:
          path: /openapi.json
          method: ANY
          private: false
```
