### ISSUE TITLE
How reach Swagger docs under Traefik proxy? 

### ISSUE THREAD

**Issue by al-yakubovich** [tiangolo/fastapi#3320]
Hi! I have docker-compose file with the following services:

```
services:

  reverse-proxy:
    image: traefik:v2.4
    container_name: reverse-proxy
    command: 
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80"
      - "8080:8080"
    labels:
      - traefik.enable=true
      - traefik.docker.network=pred-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pred-network

  api-service:
    image: x86_64/prediction-service:0.8.1
    container_name: api-service
    environment:
      SERVING_SERVICE: model-service
    expose:
      - 8000
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-service.rule=Host(`api.service.localhost`)
    networks:
      - pred-network
```

Container api-service has python script with one path for POST requests: http://api.service.localhost/predict/. This path works perfectly for POST requests. It looks like Swagger docs should be under http://api.service.localhost/docs/. But when I go to this page I am getting:

```
Not Found
HTTP Error 404. The requested resource is not found.
```

Environment:
```
python==3.8
uvicorn==0.13.4
fastapi==0.63.0
python-multipart==0.0.5
numpy~=1.19.5
Pillow==7.0.0
min-tfs-client==1.0.2
```

I would appreciate any ideas!

**Comment by STeveShary** [comment]
Shot in the dark on this one... Maybe remove the trailing slash?  so change it to http://api.service.localhost/docs

Proxies can get really weird with trailing slashes.

This is the init method for fast api and it doesn't have a trailing slash.  You can also add that when you instantiate FastAPI.  

```
class FastAPI(Starlette):
    def __init__(
        self,
        *,
        debug: bool = False,
        routes: Optional[List[BaseRoute]] = None,
        title: str = "FastAPI",
        description: str = "",
        version: str = "0.1.0",
        openapi_url: Optional[str] = "/openapi.json",
        openapi_tags: Optional[List[Dict[str, Any]]] = None,
        servers: Optional[List[Dict[str, Union[str, Any]]]] = None,
        dependencies: Optional[Sequence[Depends]] = None,
        default_response_class: Type[Response] = Default(JSONResponse),
        docs_url: Optional[str] = "/docs",
        [...]

```

**Comment by al-yakubovich** [comment]
Removing the trailing slash does not help :(

**Comment by al-yakubovich** [comment]
But if I add 
```
    ports:
      - "8070:80"    
```
into **api-service**  I can generate docs under: http://localhost:8070/docs
So it looks like there is some problem with ports mapping

**Comment by al-yakubovich** [comment]
@gyKa 
Thanks. I added `app = FastAPI(root_path="/api/v1")` to script but I still cannot connect. 

Also tried to change docker-compose so webapp could have only two pathes:
```
http://traefik.service.localhost/ -> Traefik UI
http://api.service.localhost/ -> 'Hello-Word' page from api-service
```
But it does not work either


Here is my updated docker-compose file:


```
version: '3.8'

services:
  reverse-proxy:
    image: traefik:v2.4
    container_name: reverse-proxy
    command: 
      - "--api.dashboard"
      - "--providers.docker"
    ports:
      - "80:80"
      - "8080:8080"
    labels:
      - traefik.http.routers.traefik.rule=Host(`traefik.service.localhost`)
      - traefik.http.routers.traefik.service=api@internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pred-network
  api-service:
    image: x86_64/prediction-service:0.8.1
    container_name: api-service
    environment:
      SERVING_SERVICE: model-service
    expose:
      - 80
    labels:
      - traefik.http.routers.service.rule=Host(`api.service.localhost`)
      - traefik.http.services.service.loadbalancer.server.port=80
    networks:
      - pred-network

networks:
  pred-network:
```
