### ISSUE TITLE
"Examples" empty select box in Swagger UI doc

### ISSUE THREAD

**Issue by otsuka** [tiangolo/fastapi#363]
I run the sample notes app of [the tutorial](https://fastapi.tiangolo.com/tutorial/async-sql-databases/).

Opening the API documentation with Swagger UI, I found an empty select box labeled "Examples" in Request body block as images below.

What is this select box? What is this use?
How can I set a value in the select box?

![AwesomeScreenshot-Fast-API-Swagger-UI-2019-07-03-12-07-34](https://user-images.githubusercontent.com/1156160/60561206-b68aa580-9d8d-11e9-9c3f-4b1a83ab895d.png)

###### `Try it out` button Clicked

![AwesomeScreenshot-Fast-API-Swagger-UI-2019-07-03-12-07-71](https://user-images.githubusercontent.com/1156160/60561208-b8ecff80-9d8d-11e9-8eb5-af3ab1370e8f.png)

**Comment by dmontagu** [comment]
Oh man, this looks like it could be really useful as a way to quickly convey/grasp how a given endpoint should be used (especially if the endpoint has a complex or deeply/variably-nested input model).

@tiangolo if https://github.com/samuelcolvin/pydantic/pull/663 makes it possible to easily add examples that can be selected in this drop down, I think that will be worth a specific call-out in the fastapi docs!

**Comment by eabrouwer3** [comment]
This should work in your case. I'm wondering. Should we add it to the fastapi docs where the previously mentioned `example` property could be set for a specific response (["Additional Responses in OpenAPI"](https://fastapi.tiangolo.com/tutorial/additional-responses/))? Or should we add it maybe to the ["Extending OpenAPI"](https://fastapi.tiangolo.com/tutorial/extending-openapi/) section? Or somewhere else entirely, like [here](https://fastapi.tiangolo.com/tutorial/body/) where it talks about Pydantic models for the first time? Thoughts?

**Comment by fgimian** [comment]
It seems this has been merged in Pydantic.  I'm hoping it'll allow us to specify examples in the OpenAPI JSON with FastAPI as per the following snippet from the petstore example:

```
      parameters:
        - name: api_key
          in: header
          required: false
          schema:
            type: string
          example: "Bearer <TOKEN>"
        - name: petId
          in: path
          description: Pet id to delete
          required: true
          schema:
            type: integer
            format: int64
```

In our case, we have rather complex data inputs and many many parameters for various API endpoints.  Having real examples of what the expected input data looks like would be greatly beneficial to consumers of our API.

Thanks heaps guys
Fotis
