### ISSUE TITLE
Partially update a JSON file in FastAPI

### ISSUE THREAD

**Issue by innat** [tiangolo/fastapi#4788]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from fastapi import FastAPI
from fastapi.encoders import jsonable_encoder 
from pydantic import BaseModel 
app = FastAPI()
```
```yaml
get_json_file = <read_from_disk> # no database 
root
 new_folder
   type: 'apple'
   format: 'png'
   count: 10
 old_folder
   type:
     sub_type: ['a', 'b', 'c']
     count: [2, 3, 4]
 upcoming_folder:
   type: '3D'
   format: ['.dicom', 'mha', 'nii']
```
 
```python 
@app.patch("/items/{item_id}", response_model=Item)
async def update_item(item_id: str, item: Item):
    # Read JSON file. And,
    # update specific value of it.
    # and return a updated json file. 
```

### Description

I'm new to FastAPI. I've read the documentation, [here](https://fastapi.tiangolo.com/tutorial/body-updates/), but couldn't resolve this.  I also searched online, some SO question-answer were useful. But my requirements are too simple, there is no database to get. 

The only thing I need to consider is to partially update some value of the JSON file (code above). Also, To get some values from the end-point, do I need to make an HTML page? From the end-point, can I pass multiple values to update this JSON file? 

I mention my JSON file structure above. Now I can update some specific values of it. For example, 

```python
@app.patch("/items/{item_id}", response_model=Item)
   root['new_folder']['type'] = 'oragen' # replacing apple
   root['new_folder']['format'] = '.jpg'
   root[' upcoming_folder']['format'] = ['.dicom', 'nii', 'png']
   root[' upcoming_folder']['type'] = '2D'
```

### Operating System

Windows

### FastAPI Version

`0.70.1`

### Python Version

`3.9`
