### ISSUE TITLE
How to setup a remote debugger with vscode

### ISSUE THREAD

**Issue by Msordet** [tiangolo/fastapi#707]
**Description**

Hi, I am trying to set up the vscode debugger with a remote container for FastAPI.
Here's my `launch.json`:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Attacher",
            "type": "python",
            "request": "attach",
            "port": 5678,
            "host": "localhost",
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "/app"
                }
            ]
        }
    ]
}
```

In my docker-compose file, I export the ports 5678 (debugger) and 8000 (api) and the command is: `uvicorn myapp.main:app --host 0.0.0.0 --port 8000 --reload`
.

In `main.py`, I've added the followling lines before `uvicorn.run(...)`:
```python
import ptvsd

ptvsd.enable_attach(address=('0.0.0.0', 5678), redirect_output=True)
```

When I try to run the debugger, I have this error happening in the vscode console (Help > Toggle Developer Tools):
```
  ERR timeout after 500 ms: Error: timeout after 500 ms
    at t.RawDebugSession.handleErrorResponse (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2798:1003)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2798:434
    at async t.RawDebugSession.shutdown (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2796:536)
    at async file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5182:409
```

In my process I checked a lot of resources to no avail such as:

* [Remote debugging in Docker (for Django apps)](https://gist.github.com/veuncent/1e7fcfe891883dfc52516443a008cfcb)
* https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/7

**Comment by khambadkone** [comment]
I had a similar issue on my Mac, and it was due to mono not being installed (https://www.mono-project.com/download/stable/) and also not set-up on my path. via export PATH=/Library/Frameworks/Mono.framework/Versions/Current/bin/:${PATH}
This was causing the debugger to throw the same 500 errors.

**Comment by NumanIjaz** [comment]
@Msordet did you find any solution to this problem?

**Comment by mcauto** [comment]
same here..
Did you solve it?

**Comment by mcauto** [comment]
I solve it.

https://github.com/mcauto/todo-list-fastapi/tree/master

**Comment by paxcodes** [comment]
I was able to debug by following the [docs in VS Code](https://code.visualstudio.com/docs/containers/debug-python#_how-to-enable-hot-reloading-in-django-or-flask-apps) but instead of adding `debugpy.listen(5678)` as they have suggested, I put in `debugpy.listen(("0.0.0.0", 5678))`

My docker-compose setup is based on the full-stack-fastapi-postgresql cookiecutter provided by tiangolo.

**Comment by Kludex** [comment]
There's no need for Python code: https://github.com/Kludex/fastapi-docker-debug

**Comment by TheCDC** [comment]
@Kludex I used your solution as a template and I can debug and hit breakpoints, thank you.

Launch.json
```
{
  "configurations": [
    {
      "name": "Python: Remote Attach",
      "type": "python",
      "request": "attach",
      "port": 5678,
      "host": "localhost",
      "pathMappings": [
        {
          "localRoot": "${workspaceFolder}/app",
          "remoteRoot": "/app"
        }
      ]
    }
  ]
}
```

docker-compose.debug.yml
```
version: "3.3"
services:
  backend:
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      # Allow explicit env var override for tests
      - SMTP_HOST=${SMTP_HOST}    
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    command:
      [
        "sh",
        "-c",
        "pip install debugpy && python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000",
      ]
    volumes:
      - ./backend/app:/app
    ports:
      - 8000:8000
      - 5678:5678


networks:
  traefik-public:
    # For local dev, don't expect an external Traefik network
    external: false
```

Command to run backend in debug mode

`docker-compose -f docker-compose.debug.yml up`
